services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    working_dir: /home/dynamodblocal
    volumes:
      - dynamodb_data:/home/dynamodblocal
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symptom-checker
    ports:
      - "8080:8080"
    environment:
      - amazon.dynamodb.endpoint=http://dynamodb-local:8000
      - amazon.accessKeyId=dummy
      - amazon.secretKeyId=dummy
      - amazon.region=eu-west-2
    depends_on:
      - dynamodb-local
    restart: always
    entrypoint: ["/bin/sh", "-c", "sleep 10 && java -jar app.jar"]

volumes:
  dynamodb_data:
